### PR TITLE
ignore GTK warnings

### LINKED ISSUE #13: Cannot render on Linux because of "gtk theme"
Hello,

When trying to render on Ubuntu Linux 4.17.11-041711-generic I get the following error :
```
Theme parsing error: gtk.css:6777:29: Missing opening bracket in color definition
```

Here is a demo of the issue : https://asciinema.org/a/nrVz5y3NxIXMDL99Y7NrNh90q

I don't really understand how this error makes it impossible for the app to work as I run many other Electron apps on my desktop and have never had such a problem (where the app will simply die for no apparent reason)

The theme file isn't even mine, pretty sure it is a standard theme that came with Ubuntu.

### PR DESCRIPTION
**Pull request by oliversturm**
fixes #13

### CODE REVIEW

**Comment by Ambro17** [comment]
Will this ever be merged?

**Comment by AleCandido** [comment]
We are in 2020 and still `render` is not working because of gtk warnings...

**Comment by miraclx** [comment]
Ignore GTK warnings because of borked themes...cool
What happens when you have some other form of warning?

Would be best to check the return code of the process before judging it's entire execution by a single buffer from `stdout`.

This would fix #13, #87, #90, #79, #96.

**Comment by miraclx** [comment]
The underlying issue is described here
#102

And fixed on PR #97

**Comment by faressoft** [comment]
Fixed in #97

**Pull request closed without merging**
