### PR TITLE
ignore GTK warnings

### LINKED ISSUE #13: Cannot render on Linux because of "gtk theme"
Hello,

When trying to render on Ubuntu Linux 4.17.11-041711-generic I get the following error :
```
Theme parsing error: gtk.css:6777:29: Missing opening bracket in color definition
```

Here is a demo of the issue : https://asciinema.org/a/nrVz5y3NxIXMDL99Y7NrNh90q

I don't really understand how this error makes it impossible for the app to work as I run many other Electron apps on my desktop and have never had such a problem (where the app will simply die for no apparent reason)

The theme file isn't even mine, pretty sure it is a standard theme that came with Ubuntu.

### PR DESCRIPTION
**Pull request by oliversturm**
fixes #13

### CODE REVIEW

**Comment by MaximDevoir** [comment]
Awesome work.

Should the GTK fix be on its own branch, separate from the package updates?

+1 needs review and merging @faressoft

**Comment by oliversturm** [comment]
Both my pull requests can go together, but they turned out to be independent so I kept them separate.

**Comment by oliversturm** [comment]
Sorry, late night comment that last one - I realize that this pull request has received unrelated commits because it was stupidly done from the master branch of my fork. Will close this and resubmit separately in a moment.

**Comment by miraclx** [comment]
The underlying issue is described here
#102

And fixed on PR #97

**Pull request closed without merging**
